### ISSUE TITLE
Reduce performance

### ISSUE THREAD

**Issue by WilliamAnimate** [DuckOS-GitHub/DuckOS#1]
![image](https://user-images.githubusercontent.com/75321465/186763622-295df9e1-eb58-4528-8ca1-bccc97638217.png)
i have no comment lmao
HOW TO FIX THE ISSUE:
do ``"A open-sourced Windows operating system, which is a modification of the original windows 10, designed to improve performance and reduce latency."``

**Comment by WilliamAnimate** [comment]
@fikinoob take a look :)

**Comment by fikinoob** [comment]
blame autocorrect
