### ISSUE TITLE
m a j o r   g r a m m e r   m i s t a k e

### ISSUE THREAD

**Issue by WilliamAnimate** [DuckOS-GitHub/DuckOS#3]
![image](https://user-images.githubusercontent.com/75321465/186765109-bb044cbd-4bc1-43c5-845b-7085db33ec1d.png)
:trollface: I'm not stopping until every epelling/grammer mistake is fixed

**Comment by WilliamAnimate** [comment]
so replace it with ``an explaination`` @fikinoob

**Comment by fikinoob** [comment]
okay
