### ISSUE TITLE
User account picture is inconsistent with wallpaper

### ISSUE THREAD

**Issue by WilliamAnimate** [DuckOS-GitHub/DuckOS#49]
### Describe the bug

ok this time not a readme bug. i swear
https://github.com/DuckOS-GitHub/DuckOS/blob/main/src/ProgramData/Microsoft/User%20Account%20Pictures/user-192.png is related to old duck wallpaper or something
however, this https://github.com/DuckOS-GitHub/DuckOS/blob/main/src/Web/Wallpaper/img0.jpg is new, and that is old

*maybe sample something?*

### To Reproduce

**NOT SOMETHING THIS BUTTON NO WORK AA**

### Expected behaviour

idk, consistant user profile picture and stuff?

### Screenshots / Videos

# **nah**

### Desktop Info

# **its just images bro**
intel cpu CPU (Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz)
system drive type: SSD (also has an HHD but not hosted on this)
os: windows 11 stock (ew) build 2200.1219

### Additional Context

# **nein, non, no**

**Comment by AnhNguyenlost13** [comment]
Man, this makes me want to enable blank issues for stuffs like this

**Comment by fikinoob** [comment]
now put the sun

![THE SUN](https://cdn.discordapp.com/attachments/1018856737970860082/1043523090686169170/smh.png)

**Comment by WilliamAnimate** [comment]
LMAO reenable blank issues momento
