### ISSUE TITLE
Make it easier installing on real machine

### ISSUE THREAD

**Issue by WilliamAnimate** [DuckOS-GitHub/DuckOS#50]
### Describe the bug

so @fikinoob forced me to install duckos on my host machine and i cant install!!11`!

to fix: bundle drivers by default

### To Reproduce

buy a usb drive. i would recommend at least 32 gb
have a drive big enough to fit duckos and post oobe+post pis

### Expected behaviour

work like an actual windows 10 installation

### Screenshots / Videos

no.you have a machine of youR oWNN

### Desktop Info

i forgor i try inmstall on hhd no bitlocker

### Additional Context

fikI

**Comment by WilliamAnimate** [comment]
what do you mean give me your drivers??!!

**Comment by WilliamAnimate** [comment]
![image](https://user-images.githubusercontent.com/75321465/202915636-bb40aec2-62ea-4874-87c3-c6cbc87b9185.png)
(context)

**Comment by WilliamAnimate** [comment]
**skill issue**

**Comment by fikinoob** [comment]
your gonna be stuck in my basement until you give me those drivers

**Comment by WilliamAnimate** [comment]
let me out
**LET ME OUT**
# **LET ME OUT**
# OPEN THE DOOR

**Comment by fikinoob** [comment]
![image](https://user-images.githubusercontent.com/89738697/202915695-70c57e4d-4fa4-432b-8099-f8af9145cef2.png)
smh install the newer when it comes out

**Comment by WilliamAnimate** [comment]
stop correcting my spelling mistake 😠 >:(

**Comment by WilliamAnimate** [comment]
@fikinoob did you fix it
