### ISSUE TITLE
Readme nonsense REBORN

### ISSUE THREAD

**Issue by WilliamAnimate** [DuckOS-GitHub/DuckOS#6]
![image](https://user-images.githubusercontent.com/75321465/188248717-38bc368a-6b44-479d-9ada-3223f9e66e42.png)
do you see it?
no???
![image](https://user-images.githubusercontent.com/75321465/188248797-925e3495-912f-41c3-9da1-5d3cf3b1215f.png)
you still need to refix https://github.com/DuckOS-GitHub/DuckOS/issues/1, but its in readme.md

**Comment by fikinoob** [comment]
What
