### ISSUE TITLE
inconsistency with your operating sUStem

### ISSUE THREAD

**Issue by WilliamAnimate** [DuckOS-GitHub/DuckOS#7]
``![image](https://user-images.githubusercontent.com/75321465/188248926-f4bb63a1-ccd4-40fe-885c-c7b899a26e7f.png)``
in readme.md go to the place where it says "Why should we trust you" and replace it with the link above

(ok amogus aint funny anymore :suspect: :suspect: :suspect: :suspect: :suspect: :suspect: :suspect: :suspect: :suspect: :suspect: :suspect: :suspect: ??????

**Comment by fikinoob** [comment]
sussy
