### ISSUE TITLE
"In America, the users trust you, in Soviet Russia, YOU TRUST USERS"

### ISSUE THREAD

**Issue by WilliamAnimate** [DuckOS-GitHub/DuckOS#8]
we go to America.
``why you should trust us``
![image](https://user-images.githubusercontent.com/75321465/188249048-9da8f83f-44ec-4251-b750-77b3820c1385.png)
fix that. you dont trust the users for the pull requests, the users trust you for the iso on host machine friend

**Comment by fikinoob** [comment]
It's only me as the developer kekw
